# Generated by Django 5.1.5 on 2025-01-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_managing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingretiend',
            new_name='Ingredient',
        ),
    ]
