# Generated by Django 5.1.5 on 2025-01-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_managing', '0002_rename_ingretiend_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
