# Generated by Django 5.1.5 on 2025-01-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_managing', '0003_ingredient_price_ingredient_quant_recipe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quant',
            field=models.IntegerField(default=0),
        ),
    ]
